import type { CelestialBody } from '@/types/astronomy';

export const CELESTIAL_BODIES: CelestialBody[] = [
  {
    name: 'Moon',
    displayName: 'Moon',
    category: 'moon',
    magnitude: -12.7,
    description: 'Our nearest celestial neighbor, its craters and maria visible to the naked eye.',
    funFact: 'The Moon is moving away from Earth at about 3.8 cm per year.',
    difficulty: 'naked-eye',
    color: 'text-yellow-200',
    iconType: 'crescent',
  },
  {
    name: 'Venus',
    displayName: 'Venus',
    category: 'planet',
    magnitude: -4.5,
    description: 'The brightest planet, often visible at dusk or dawn as the "Evening Star".',
    funFact: 'Venus rotates backwards compared to most planets — the Sun rises in the west there.',
    difficulty: 'naked-eye',
    color: 'text-amber-200',
    iconType: 'circle',
  },
  {
    name: 'Mars',
    displayName: 'Mars',
    category: 'planet',
    magnitude: -2.9,
    description: 'The Red Planet, with its distinctive ruddy glow caused by iron oxide on its surface.',
    funFact: 'A day on Mars is just 40 minutes longer than a day on Earth.',
    difficulty: 'naked-eye',
    color: 'text-red-400',
    iconType: 'circle',
  },
  {
    name: 'Jupiter',
    displayName: 'Jupiter',
    category: 'planet',
    magnitude: -2.9,
    description: 'The king of planets — its cloud bands and four Galilean moons visible in binoculars.',
    funFact: 'Jupiter\'s Great Red Spot is a storm that has raged for over 350 years.',
    difficulty: 'naked-eye',
    color: 'text-orange-300',
    iconType: 'circle',
  },
  {
    name: 'Saturn',
    displayName: 'Saturn',
    category: 'planet',
    magnitude: 0.6,
    description: 'The jewel of the solar system — its spectacular rings visible through a small telescope.',
    funFact: 'Saturn\'s rings are made mostly of ice particles and are only about 10 meters thick.',
    difficulty: 'naked-eye',
    color: 'text-yellow-300',
    iconType: 'circle',
  },
  {
    name: 'Mercury',
    displayName: 'Mercury',
    category: 'planet',
    magnitude: -1.9,
    description: 'The elusive innermost planet, rarely visible and always near the horizon at twilight.',
    funFact: 'Mercury has no seasons — its axial tilt is nearly zero degrees.',
    difficulty: 'naked-eye',
    color: 'text-gray-400',
    iconType: 'circle',
  },
  {
    name: 'Uranus',
    displayName: 'Uranus',
    category: 'planet',
    magnitude: 5.7,
    description: 'The ice giant that rolls on its side — barely visible to the naked eye in dark skies.',
    funFact: 'Uranus rotates on its side with an axial tilt of 98 degrees.',
    difficulty: 'binoculars',
    color: 'text-cyan-300',
    iconType: 'circle',
  },
  {
    name: 'Neptune',
    displayName: 'Neptune',
    category: 'planet',
    magnitude: 7.8,
    description: 'The distant blue giant — requires binoculars or a telescope to spot.',
    funFact: 'Winds on Neptune can reach 2,100 km/h, the fastest in the solar system.',
    difficulty: 'binoculars',
    color: 'text-blue-400',
    iconType: 'circle',
  },
  {
    name: 'M31',
    displayName: 'Andromeda Galaxy',
    category: 'dso',
    magnitude: 3.4,
    description: 'Our nearest galactic neighbor — a spiral galaxy containing a trillion stars.',
    funFact: 'Andromeda is on a collision course with the Milky Way, arriving in ~4.5 billion years.',
    difficulty: 'naked-eye',
    color: 'text-purple-300',
    iconType: 'galaxy',
  },
  {
    name: 'M42',
    displayName: 'Orion Nebula',
    category: 'dso',
    magnitude: 4.0,
    description: 'A stellar nursery where new stars are born, visible as a fuzzy star in Orion\'s sword.',
    funFact: 'The Orion Nebula is about 1,344 light-years away and 24 light-years across.',
    difficulty: 'naked-eye',
    color: 'text-pink-300',
    iconType: 'star',
  },
  {
    name: 'M45',
    displayName: 'Pleiades',
    category: 'dso',
    magnitude: 1.6,
    description: 'The Seven Sisters — one of the most famous star clusters, visible to the naked eye.',
    funFact: 'The Pleiades are only 100 million years old — young by stellar standards.',
    difficulty: 'naked-eye',
    color: 'text-blue-200',
    iconType: 'star',
  },
  {
    name: 'M13',
    displayName: 'Hercules Cluster',
    category: 'dso',
    magnitude: 5.8,
    description: 'A globular cluster of 300,000 stars — a stunning sight through binoculars.',
    funFact: 'In 1974, we sent a radio message toward M13. It will arrive in about 25,000 years.',
    difficulty: 'binoculars',
    color: 'text-yellow-100',
    iconType: 'star',
  },
];

export const BODY_MAP = new Map(CELESTIAL_BODIES.map(b => [b.name, b]));

// Bodies supported by astronomy-engine's Astronomy.Body enum
export const ENGINE_BODIES = [
  'Moon', 'Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune',
] as const;
