import type { CelestialBody } from '@/types/astronomy';

export const CELESTIAL_BODIES: CelestialBody[] = [
  {
    name: 'Moon',
    displayName: 'Moon',
    category: 'moon',
    magnitude: -12.7,
    description: 'Our nearest celestial neighbor, its craters and maria visible to the naked eye.',
    funFact: 'The Moon is moving away from Earth at about 3.8 cm per year.',
    difficulty: 'naked-eye',
    color: 'text-yellow-200',
    iconType: 'crescent',
  },
  {
    name: 'Venus',
    displayName: 'Venus',
    category: 'planet',
    magnitude: -4.5,
    description: 'The brightest planet, often visible at dusk or dawn as the "Evening Star".',
    funFact: 'Venus rotates backwards compared to most planets — the Sun rises in the west there.',
    difficulty: 'naked-eye',
    color: 'text-amber-200',
    iconType: 'circle',
  },
  {
    name: 'Mars',
    displayName: 'Mars',
    category: 'planet',
    magnitude: -2.9,
    description: 'The Red Planet, with its distinctive ruddy glow caused by iron oxide on its surface.',
    funFact: 'A day on Mars is just 40 minutes longer than a day on Earth.',
    difficulty: 'naked-eye',
    color: 'text-red-400',
    iconType: 'circle',
  },
  {
    name: 'Jupiter',
    displayName: 'Jupiter',
    category: 'planet',
    magnitude: -2.9,
    description: 'The king of planets — its cloud bands and four Galilean moons visible in binoculars.',
    funFact: 'Jupiter\'s Great Red Spot is a storm that has raged for over 350 years.',
    difficulty: 'naked-eye',
    color: 'text-orange-300',
    iconType: 'circle',
  },
  {
    name: 'Saturn',
    displayName: 'Saturn',
    category: 'planet',
    magnitude: 0.6,
    description: 'The jewel of the solar system — its spectacular rings visible through a small telescope.',
    funFact: 'Saturn\'s rings are made mostly of ice particles and are only about 10 meters thick.',
    difficulty: 'naked-eye',
    color: 'text-yellow-300',
    iconType: 'circle',
  },
  {
    name: 'Mercury',
    displayName: 'Mercury',
    category: 'planet',
    magnitude: -1.9,
    description: 'The elusive innermost planet, rarely visible and always near the horizon at twilight.',
    funFact: 'Mercury has no seasons — its axial tilt is nearly zero degrees.',
    difficulty: 'naked-eye',
    color: 'text-gray-400',
    iconType: 'circle',
  },
  {
    name: 'Uranus',
    displayName: 'Uranus',
    category: 'planet',
    magnitude: 5.7,
    description: 'The ice giant that rolls on its side — barely visible to the naked eye in dark skies.',
    funFact: 'Uranus rotates on its side with an axial tilt of 98 degrees.',
    difficulty: 'binoculars',
    color: 'text-cyan-300',
    iconType: 'circle',
  },
  {
    name: 'Neptune',
    displayName: 'Neptune',
    category: 'planet',
    magnitude: 7.8,
    description: 'The distant blue giant — requires binoculars or a telescope to spot.',
    funFact: 'Winds on Neptune can reach 2,100 km/h, the fastest in the solar system.',
    difficulty: 'binoculars',
    color: 'text-blue-400',
    iconType: 'circle',
  },
  {
    name: 'Sirius',
    displayName: 'Sirius',
    category: 'star',
    magnitude: -1.46,
    description: 'The brightest star in the night sky, blazing in Canis Major with a blue-white shimmer.',
    funFact: 'Sirius is actually a binary system: the visible star Sirius A and the faint white dwarf Sirius B.',
    difficulty: 'naked-eye',
    color: 'text-sky-100',
    iconType: 'star',
  },
  {
    name: 'Canopus',
    displayName: 'Canopus',
    category: 'star',
    magnitude: -0.74,
    description: 'A brilliant southern star that skims low for many northern observers.',
    funFact: 'Canopus is about 10,000 times more luminous than the Sun.',
    difficulty: 'naked-eye',
    color: 'text-amber-100',
    iconType: 'star',
  },
  {
    name: 'Arcturus',
    displayName: 'Arcturus',
    category: 'star',
    magnitude: -0.05,
    description: 'A vivid orange giant in Bootes, easy to spot in spring and early summer evenings.',
    funFact: 'Arcturus is speeding through our part of the galaxy at unusually high velocity.',
    difficulty: 'naked-eye',
    color: 'text-orange-200',
    iconType: 'star',
  },
  {
    name: 'Vega',
    displayName: 'Vega',
    category: 'star',
    magnitude: 0.03,
    description: 'A piercing blue-white star in Lyra and one of the three stars of the Summer Triangle.',
    funFact: 'Around 12,000 BCE, Vega served as Earth’s north pole star.',
    difficulty: 'naked-eye',
    color: 'text-cyan-100',
    iconType: 'star',
  },
  {
    name: 'Capella',
    displayName: 'Capella',
    category: 'star',
    magnitude: 0.08,
    description: 'A golden beacon in Auriga that dominates the winter sky.',
    funFact: 'Capella appears as one star but is actually a compact multiple-star system.',
    difficulty: 'naked-eye',
    color: 'text-yellow-100',
    iconType: 'star',
  },
  {
    name: 'Rigel',
    displayName: 'Rigel',
    category: 'star',
    magnitude: 0.13,
    description: 'The blue-white foot of Orion, bright and easy to recognize on clear winter nights.',
    funFact: 'Rigel is a blue supergiant that would engulf Mercury’s orbit if placed where our Sun is.',
    difficulty: 'naked-eye',
    color: 'text-blue-100',
    iconType: 'star',
  },
  {
    name: 'Procyon',
    displayName: 'Procyon',
    category: 'star',
    magnitude: 0.34,
    description: 'A bright nearby star in Canis Minor that forms the Winter Triangle with Sirius and Betelgeuse.',
    funFact: 'Procyon also has a white dwarf companion, though it is not visible without a telescope.',
    difficulty: 'naked-eye',
    color: 'text-amber-50',
    iconType: 'star',
  },
  {
    name: 'Betelgeuse',
    displayName: 'Betelgeuse',
    category: 'star',
    magnitude: 0.42,
    description: 'The famous reddish shoulder of Orion, huge, variable, and unmistakable.',
    funFact: 'If Betelgeuse replaced the Sun, it would likely extend beyond Mars.',
    difficulty: 'naked-eye',
    color: 'text-red-200',
    iconType: 'star',
  },
  {
    name: 'Aldebaran',
    displayName: 'Aldebaran',
    category: 'star',
    magnitude: 0.85,
    description: 'The orange eye of Taurus, glowing near the Hyades cluster.',
    funFact: 'Aldebaran only appears to sit in the Hyades; it is actually much closer to us.',
    difficulty: 'naked-eye',
    color: 'text-orange-300',
    iconType: 'star',
  },
  {
    name: 'Spica',
    displayName: 'Spica',
    category: 'star',
    magnitude: 0.98,
    description: 'A blue-white star in Virgo and one of the brightest signposts of spring.',
    funFact: 'Spica is a close binary whose two hot stars distort each other’s shapes.',
    difficulty: 'naked-eye',
    color: 'text-blue-200',
    iconType: 'star',
  },
  {
    name: 'Altair',
    displayName: 'Altair',
    category: 'star',
    magnitude: 0.77,
    description: 'A bright summer star in Aquila and another anchor of the Summer Triangle.',
    funFact: 'Altair spins so fast that it is noticeably flattened at the poles.',
    difficulty: 'naked-eye',
    color: 'text-white',
    iconType: 'star',
  },
  {
    name: 'Deneb',
    displayName: 'Deneb',
    category: 'star',
    magnitude: 1.25,
    description: 'A distant supergiant in Cygnus that completes the Summer Triangle with Vega and Altair.',
    funFact: 'Deneb is so luminous that even from over 2,000 light-years away it still shines as a first-magnitude star.',
    difficulty: 'naked-eye',
    color: 'text-slate-100',
    iconType: 'star',
  },
  {
    name: 'M31',
    displayName: 'Andromeda Galaxy',
    category: 'dso',
    magnitude: 3.4,
    description: 'Our nearest galactic neighbor — a spiral galaxy containing a trillion stars.',
    funFact: 'Andromeda is on a collision course with the Milky Way, arriving in ~4.5 billion years.',
    difficulty: 'naked-eye',
    color: 'text-purple-300',
    iconType: 'galaxy',
  },
  {
    name: 'M42',
    displayName: 'Orion Nebula',
    category: 'dso',
    magnitude: 4.0,
    description: 'A stellar nursery where new stars are born, visible as a fuzzy star in Orion\'s sword.',
    funFact: 'The Orion Nebula is about 1,344 light-years away and 24 light-years across.',
    difficulty: 'naked-eye',
    color: 'text-pink-300',
    iconType: 'star',
  },
  {
    name: 'M45',
    displayName: 'Pleiades',
    category: 'dso',
    magnitude: 1.6,
    description: 'The Seven Sisters — one of the most famous star clusters, visible to the naked eye.',
    funFact: 'The Pleiades are only 100 million years old — young by stellar standards.',
    difficulty: 'naked-eye',
    color: 'text-blue-200',
    iconType: 'star',
  },
  {
    name: 'M13',
    displayName: 'Hercules Cluster',
    category: 'dso',
    magnitude: 5.8,
    description: 'A globular cluster of 300,000 stars — a stunning sight through binoculars.',
    funFact: 'In 1974, we sent a radio message toward M13. It will arrive in about 25,000 years.',
    difficulty: 'binoculars',
    color: 'text-yellow-100',
    iconType: 'star',
  },
];

export const BODY_MAP = new Map(CELESTIAL_BODIES.map(b => [b.name, b]));

// Bodies supported by astronomy-engine's Astronomy.Body enum
export const ENGINE_BODIES = [
  'Moon', 'Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune',
] as const;
